In [ ]:
with open('addata.txt') as f:
    contents = f.read()
    print(contents)

In [2]:
import urllib

In [5]:
for line in urllib.request.urlopen("https://www.yahoo.com/ads.txt"):
    print(line)

b'#2022-06-09\n'
b'\n'
b'# ownerdomain=yahooinc.com\n'
b'\n'
b'#NAR\n'
b'\n'
b'#NAR Direct\n'
b'advertising.com, 3679, DIRECT #video, US\n'
b'advertising.com, 28090, DIRECT\n'
b'yahoo.com, 1, DIRECT #native\n'
b'yahoo.com, 52469, DIRECT #display, Yahoo\n'
b'yahoo.com, 57316, DIRECT #display, AOL\n'
b'yahoo.com, 57322, DIRECT #display, AOL\n'
b'yahoo.com, 2c44cbf8d10e3e7e1a28056c484eac0bde0af585, DIRECT #native\n'
b'yahoo.com, 29284317594, DIRECT #banner\n'
b'yahoo.com, 20459933223, DIRECT #banner\n'
b'yahoo.com, 20764982904, DIRECT #banner\n'
b'yahoo.com, 25980889636, DIRECT #banner, CA\n'
b'yahoo.com, 26720242308, DIRECT #banner, CA\n'
b'yahoo.com, 29284317576, DIRECT #banner\n'
b'yahoo.com, 29284317581, DIRECT #banner, video\n'
b'yahoo.com, 29228548013, DIRECT #banner, US\n'
b'yahoo.com, 55990, DIRECT #Native\n'
b'yahoo.com, 58761, DIRECT\n'
b'\n'
b'#ABP\n'
b'aax.media, AAXT6MET1, DIRECT #abp\n'
b'aax.media, AAXNNB5J4, DIRECT #abp\n'
b'Media.net, 8PR6YK195, RESELLER #abp\n'
b'sharethrough.com, aab3fb7d, RESELLER, d53b998a7bd4ecd2 #abp\n'
b'indexexchange.com, 192393, RESELLER #abp\n'
b'indexexchange.com, 189372, RESELLER, 50b1c356f2c5c8fc #abp\n'
b'appnexus.com, 3153, RESELLER, f5ab79cb980f11d1 #abp\n'
b'pubmatic.com, 158261, RESELLER, 5d62403b186f2ace #abp\n'
b'adpushup.com, fd0270fef2e04a75cf3eb057fc34dc14, DIRECT, b0b8ff8485794fdd #abp\n'
b'google.com, pub-5912840019437959, RESELLER, f08c47fec0942fa0 #abp\n'
b'appnexus.com, 11901, RESELLER #abp\n'
b'openx.com, 541010313, RESELLER, 6a698e2ec38604c6 #abp\n'
b'openx.com, 543731411, RESELLER, 6a698e2ec38604c6 #abp\n'
b'rubiconproject.com, 20616, RESELLER, 0bfd66d529a55807 #abp\n'
b'pubmatic.com, 158984, RESELLER, 5d62403b186f2ace #abp\n'
b'yieldmo.com, 2737698684593446924, RESELLER #abp\n'
b'sharethrough.com, 944ae2c3, RESELLER, d53b998a7bd4ecd2 #abp\n'
b'yieldmo.com, 2724005447462757095, RESELLER #abp\n'
b'rubiconproject.com, 23280, RESELLER, 0bfd66d529a55807 #abp\n'
b'onetag.com, 66d66dec41ef0cc, RESELLER #abp\n'
b'appnexus.com, 11924, RESELLER, f5ab79cb980f11d1 #abp\n'
b'sonobi.com, 969be2f789, RESELLER, d1a215d9eb5aee9e #abp\n'
b'contextweb.com, 560606, RESELLER, 89ff185a4c4e857c #abp\n'
b'33across.com, 0010b00002Mq2FYAAZ, RESELLER, bbea06d9c4d2853c #abp\n'
b'xandr.com, 11429, RESELLER, f5ab79cb980f11d1 #abp\n'
b'xandr.com, 12701, RESELLER, f5ab79cb980f11d1 #abp\n'
b'smartadserver.com,4176,RESELLER #abp\n'
b'smartadserver.com, 4102, RESELLER #abp\n'
b'smartadserver.com, 4071, RESELLER #abp\n'
b'152media.info, 152M1, RESELLER #abp\n'
b'onetag.com,62ff8a580aaea32,RESELLER #abp\n'
b'amxrtb.com,105199584,reseller #abp\n'
b'consumable.com,2000970,reseller #abp\n'
b'lijit.com,265720,reseller,fafdf38b16bf6b2b #abp\n'
b'connectad.io,217,reseller,85ac85a30c93b3e5 #abp\n'
b'appnexus.com,12290,reseller,f5ab79cb980f11d1 #abp\n'
b'indexexchange.com,191503,reseller,50b1c356f2c5c8fc #abp\n'
b'pubmatic.com,158355,reseller,5d62403b186f2ace #abp\n'
b'\n'
b'#ADX\n'
b'google.com, pub-5482278706573796, RESELLER #banner, CA\n'
b'google.com, pub-5786243031610172, DIRECT #banner, US\n'
b'indexexchange.com, 195918, RESELLER, 50b1c356f2c5c8fc\n'
b'pubmatic.com, 160938, RESELLER, 5d62403b186f2ace\n'
b'rubiconproject.com, 23798, RESELLER, 0bfd66d529a55807\n'
b'openx.com, 545697947, RESELLER\n'
b'\n'
b'#AppNexus\n'
b'appnexus.com, 273, RESELLER #banner\n'
b'appnexus.com, 1868, RESELLER #banner\n'
b'appnexus.com, 1356, RESELLER, f5ab79cb980f11d1\n'
b'appnexus.com, 11664, RESELLER #banner\n'
b'appnexus.com, 3292, RESELLER #video\n'
b'appnexus.com, 11665, RESELLER #video\n'
b'\n'
b'#Buzzfeed\n'
b'google.com, pub-9636953777155876, DIRECT, f08c47fec0942fa0\n'
b'\n'
b'#CBS\n'
b'google.com, pub-1991679624331369, RESELLER, f08c47fec0942fa0\n'
b'google.com, pub-2647493973215238, RESELLER, f08c47fec0942fa0\n'
b'google.com, pub-2679103605715789, RESELLER, f08c47fec0942fa0\n'
b'advertising.com, 28633, DIRECT\n'
b'indexexchange.com, 184819, RESELLER, 50b1c356f2c5c8fc\n'
b'lijit.com, 205858-eb, RESELLER, fafdf38b16bf6b2b\n'
b'lijit.com, 205858, RESELLER, fafdf38b16bf6b2b\n'
b'openx.com, 539022633, RESELLER, 6a698e2ec38604c6\n'
b'pubmatic.com, 157181, RESELLER, 5d62403b186f2ace\n'
b'rhythmone.com, 1708260210, RESELLER, a670c89d4a324e47\n'
b'rubiconproject.com, 17568, RESELLER, 0bfd66d529a55807\n'
b'smaato.com, 1100040447, RESELLER, 07bcf65f187117b4\n'
b'sonobi.com, 1da02e019a, RESELLER, d1a215d9eb5aee9e\n'
b'sovrn.com, 205858, RESELLER, fafdf38b16bf6b2b\n'
b'spotx.tv, 78699, RESELLER, 7842df1d2fe2db34\n'
b'spotxchange.com, 78699, RESELLER, 7842df1d2fe2db34\n'
b'telaria.com, dtq2a-09kz2, RESELLER, 1a4e959a1b50034a\n'
b'tremorhub.com, dtq2a-09kz2, RESELLER, 1a4e959a1b50034a\n'
b'triplelift.com, 7380, RESELLER, 6c33edb13117fd86\n'
b'yahoo.com, 55750, DIRECT, e1a5b5b6e3255540\n'
b'yieldmo.com, 2209431261108930012, RESELLER\n'
b'\n'
b'#Conde\n'
b'google.com, pub-3844877863303739, RESELLER, f08c47fec0942fa0\n'
b'indexexchange.com, 184912, RESELLER, 50b1c356f2c5c8fc\n'
b'spotxchange.com, 159835, RESELLER, 7842df1d2fe2db34\n'
b'spotx.tv, 159835, RESELLER, 7842df1d2fe2db34\n'
b'openx.com, 538995730, RESELLER, 6a698e2ec38604c6\n'
b'rubiconproject.com, 17814, RESELLER, 0bfd66d529a55807\n'
b'condenast.com, 108347105, DIRECT\n'
b'\n'
b'#Criteo\n'
b'criteo.com, B-039267, RESELLER, 9fac4a4a87c2a44f\n'
b'themediagrid.com, FXWU4O, RESELLER, 35d5010d7789b49d\n'
b'\n'
b'#EMX\n'
b'EMXDGT.com, 273, RESELLER, 1e1d41537f7cad7f #banner\n'
b'EMXDGT.com, 1291, RESELLER, 1e1d41537f7cad7f #video\n'
b'conversantmedia.com, 100316, RESELLER, 03113cd04947736d\n'
b'\n'
b'#GumGum\n'
b'gumgum.com, 15563, RESELLER, ffdef49475d318a9\n'
b'\n'
b'#Index\n'
b'indexexchange.com, 184110, RESELLER, 50b1c356f2c5c8fc #banner, 1M\n'
b'indexexchange.com, 183875, RESELLER, 50b1c356f2c5c8fc #banner, US\n'
b'indexexchange.com, 183965, RESELLER, 50b1c356f2c5c8fc #video\n'
b'\n'
b'#Kargo\n'
b'kargo.com, 7848, RESELLER\n'
b'indexexchange.com, 184081, RESELLER\n'
b'contextweb.com, 562001, RESELLER, 89ff185a4c4e857c\n'
b'\n'
b'#Magnite\n'
b'telaria.com,4jdlm-4qsx6,RESELLER,1a4e959a1b50034a\n'
b'tremorhub.com,4jdlm-4qsx6,RESELLER,1a4e959a1b50034a\n'
b'\n'
b'#Media.Net\n'
b'media.net, 8CU2OO4Y3, RESELLER\n'
b'media.net, 8CUSU8113, RESELLER\n'
b'yahoo.com, 59991, DIRECT #display, Yahoo\n'
b'yahoo.com, 59992, DIRECT #display, Yahoo\n'
b'media.net, 8CU8A3966, DIRECT\n'
b'triplelift.com, 12755, DIRECT, 6c33edb13117fd86\n'
b'\n'
b'#MediaGrid\n'
b'themediagrid.com, J84GRM, RESELLER, 35d5010d7789b49d\n'
b'\n'
b'#Nascar\n'
b'google.com, pub-9869390676837132, RESELLER, f08c47fec0942fa0\n'
b'appnexus.com, 9285, RESELLER # banner, video\n'
b'indexexchange.com, 193358, RESELLER, 50b1c356f2c5c8fc\n'
b'openx.com, 543993763, RESELLER, 6a698e2ec38604c6\n'
b'appnexus.com, 9475, RESELLER, f5ab79cb980f11d1\n'
b'adops.com, NASC2016, DIRECT\n'
b'pubmatic.com, 158171, RESELLER, 5d62403b186f2ace\n'
b'\n'
b'#NFL\n'
b'google.com, pub-6245227841947028, DIRECT, f08c47fec0942fa0 #video, US\n'
b'rubiconproject.com, 21840, DIRECT, 0bfd66d529a55807\n'
b'pubmatic.com, 158926, DIRECT, 5d62403b186f2ace\n'
b'rhythmone.com, 1204009095, DIRECT, a670c89d4a324e47\n'
b'openx.com, 540922801, DIRECT, 6a698e2ec38604c6\n'
b'freewheel.tv, 169843, RESELLER\n'
b'advertising.com, 28854, DIRECT, e1a5b5b6e3255540\n'
b'indexexchange.com, 193257, DIRECT\n'
b'google.com, pub-1000923676553030, DIRECT, f08c47fec0942fa0\n'
b'appnexus.com, 12428, DIRECT\n'
b'video.unrulymedia.com, 1204009095, DIRECT\n'
b'yahoo.com, 57560, DIRECT, e1a5b5b6e3255540\n'
b'adops.com, NFLL2007, DIRECT\n'
b'openx.com, 542678089, RESELLER, 6a698e2ec38604c6\n'
b'rhythmone.com, 4026021210, DIRECT, a670c89d4a324e47\n'
b'rubiconproject.com, 10736, RESELLER, 0bfd66d529a55807\n'
b'video.unrulymedia.com, 4026021210, DIRECT\n'
b'yahoo.com, 59478, DIRECT, e1a5b5b6e3255540\n'
b'triplelift.com, 12168, RESELLER, 6c33edb13117fd86\n'
b'\n'
b'#OpenX\n'
b'openx.com, 537125356, RESELLER, 6a698e2ec38604c6 #banner\n'
b'openx.com, 537143344, RESELLER, 6a698e2ec38604c6 #video\n'
b'\n'
b'#Pubmatic\n'
b'pubmatic.com, 156198, RESELLER, 5d62403b186f2ace #banner, US\n'
b'pubmatic.com, 156248, RESELLER #banner\n'
b'pubmatic.com, 157901, RESELLER, 5d62403b186f2ace #banner_performance\n'
b'pubmatic.com, 133799, RESELLER, 5d62403b186f2ace #banner\n'
b'pubmatic.com, 156078, RESELLER, 5d62403b186f2ace\n'
b'pubmatic.com, 156458, RESELLER, 5d62403b186f2ace #video\n'
b'pubmatic.com, 156674, RESELLER, 5d62403b186f2ace #video\n'
b'pubmatic.com, 157479, RESELLER, 5d62403b186f2ace #banner, US\n'
b'pubmatic.com, 161888, RESELLER, 5d62403b186f2ace #banner\n'
b'\n'
b'#Pulsepoint\n'
b'contextweb.com, 558299, RESELLER, 89ff185a4c4e857c #banner\n'
b'contextweb.com, 562437, RESELLER, 89ff185a4c4e857c #video\n'
b'\n'
b'#Rubicon\n'
b'rubiconproject.com, 13132, RESELLER, 0bfd66d529a55807 #banner\n'
b'rubiconproject.com, 17250, RESELLER, 0bfd66d529a55807 #banner\n'
b'rubiconproject.com, 18222, RESELLER, 0bfd66d529a55807 #video\n'
b'rubiconproject.com, 17960, RESELLER, 0bfd66d529a55807\n'
b'\n'
b'#Sharethrough\n'
b'sharethrough.com, c3c49548, RESELLER, d53b998a7bd4ecd2\n'
b'openx.com, 540274407, RESELLER, 6a698e2ec38604c6\n'
b'rubiconproject.com, 18694, RESELLER, 0bfd66d529a55807\n'
b'33across.com, 0013300001kQj2HAAS, RESELLER, bbea06d9c4d2853c\n'
b'spotxchange.com, 212457, RESELLER\n'
b'spotx.tv, 212457, RESELLER\n'
b'pubmatic.com, 156557, RESELLER, 5d62403b186f2ace\n'
b'smaato.com, 1100047713, RESELLER, 07bcf65f187117b4\n'
b'\n'
b'#Spot.IM\n'
b'spotim.market, sp_n93tLsKu, DIRECT, 077e5f709d15bdbb\n'
b'openweb.market, sp_n93tLsKu, DIRECT, 077e5f709d15bdbb\n'
b'spotim.market, 266658, DIRECT, 077e5f709d15bdbb\n'
b'google.com, pub-5616046187545019, DIRECT, f08c47fec0942fa0\n'
b'adtech.com, 11465, RESELLER, e1a5b5b6e3255540\n'
b'openx.com, 539466082, RESELLER, 6a698e2ec38604c6\n'
b'openx.com, 540362110, RESELLER, 6a698e2ec38604c6\n'
b'rhythmone.com, 915882568, DIRECT, a670c89d4a324e47\n'
b'rhythmone.com, 449400134, DIRECT, a670c89d4a324e47\n'
b'rubiconproject.com, 17184, DIRECT, 0bfd66d529a55807\n'
b'rubiconproject.com, 18728, DIRECT, 0bfd66d529a55807\n'
b'appnexus.com, 6933, RESELLER, f5ab79cb980f11d1\n'
b'pubMatic.com, 156813, DIRECT, 5d62403b186f2ace\n'
b'pubmatic.com, 157679, DIRECT, 5d62403b186f2ace\n'
b'adyoulike.com, e5ae8cdbe88e1f889aae7ee0c672ca30, DIRECT, 4ad745ead2958bf7\n'
b'indexexchange.com, 189478, DIRECT, 50b1c356f2c5c8fc\n'
b'indexexchange.com, 189529, DIRECT, 50b1c356f2c5c8fc\n'
b'sovrn.com, 250745, DIRECT, fafdf38b16bf6b2b\n'
b'lijit.com, 250745, DIRECT, fafdf38b16bf6b2b\n'
b'lijit.com, 250745-eb, DIRECT, fafdf38b16bf6b2b\n'
b'triplelift.com, 10504, DIRECT, 6c33edb13117fd86\n'
b'conversantmedia.com, 100292, DIRECT, 03113cd04947736d\n'
b'Kargo.com, 85923, DIRECT\n'
b'\n'
b'#Sovrn\n'
b'sovrn.com, 346033, RESELLER, fafdf38b16bf6b2b\n'
b'lijit.com, 346033, RESELLER, fafdf38b16bf6b2b\n'
b'\n'
b'#TripleLift\n'
b'triplelift.com, 2792, RESELLER, 6c33edb13117fd86\n'
b'triplelift.com, 12362-EB, RESELLER, 6c33edb13117fd86\n'
b'\n'
b'#Unruly\n'
b'video.unrulymedia.com, 1422284203, RESELLER\n'
b'\n'
b'#Xad\n'
b'xad.com, 240, RESELLER, 81cbf0a75a5e0e9a #banner\n'
b'\n'
b'#Yieldmo\n'
b'yieldmo.com, 2825328808255496712, RESELLER #ortb\n'
b'rubiconproject.com, 17070, RESELLER, 0bfd66d529a55807 #yieldmo\n'
b'contextweb.com, 561118, RESELLER, 89ff185a4c4e857c #yieldmo\n'
b'pubmatic.com, 160648, RESELLER, 5d62403b186f2ace #yieldmo\n'
b'\n'
b'#EMEA\n'
b'\n'
b'#EMEA Direct\n'
b'advertising.com, 5831, DIRECT #video\n'
b'advertising.com, 8022, DIRECT #video\n'
b'advertising.com, 8044, DIRECT #video\n'
b'yahoo.com, 53639, DIRECT\n'
b'yahoo.com, 22978591428, DIRECT #banner, DE\n'
b'yahoo.com, 25066524914, DIRECT #banner, RO\n'
b'yahoo.com, 25082361049, DIRECT #banner, AT\n'
b'yahoo.com, 25228164329, DIRECT #banner, NL\n'
b'yahoo.com, 25309916134, DIRECT #banner, IT\n'
b'yahoo.com, 25351902027, DIRECT #banner, FI\n'
b'yahoo.com, 25469906770, DIRECT #banner, SE\n'
b'yahoo.com, 25485742905, DIRECT #banner, HR\n'
b'yahoo.com, 25620564984, DIRECT #banner, LV\n'
b'yahoo.com, 25873288626, DIRECT #banner, NO\n'
b'yahoo.com, 26235095577, DIRECT #banner, IL\n'
b'yahoo.com, 26276670482, DIRECT #banner, DK\n'
b'yahoo.com, 26369917656, DIRECT #banner, SI\n'
b'yahoo.com, 26638477433, DIRECT #banner, BG\n'
b'yahoo.com, 26783299512, DIRECT #banner, UA\n'
b'yahoo.com, 26794280713, DIRECT #banner, GR\n'
b'yahoo.com, 26876032518, DIRECT #banner, FR\n'
b'yahoo.com, 27196681368, DIRECT #banner, RS\n'
b'yahoo.com, 27371993970, DIRECT #banner, TR\n'
b'yahoo.com, 27397830105, DIRECT #banner, EE\n'
b'yahoo.com, 27533633386, DIRECT #banner, BE\n'
b'yahoo.com, 27775375826, DIRECT #banner, RU\n'
b'yahoo.com, 27801211961, DIRECT #banner, HU\n'
b'yahoo.com, 27936034040, DIRECT #banner, SK\n'
b'yahoo.com, 28038767046, DIRECT #banner, UK\n'
b'yahoo.com, 28055019985, DIRECT #banner, Maktoob ENG\n'
b'yahoo.com, 28204593817, DIRECT #banner, CZ\n'
b'yahoo.com, 28339415896, DIRECT #banner, LT\n'
b'yahoo.com, 28592139538, DIRECT #banner, PL\n'
b'yahoo.com, 28752797752, DIRECT #banner, PT\n'
b'yahoo.com, 28788119718, DIRECT #banner, ES\n'
b'yahoo.com, 28871783696, DIRECT #banner, Maktoob ARA\n'
b'yahoo.com, 29005521394, DIRECT #banner, ZA\n'
b'yahoo.com, 29284317533, DIRECT #banner\n'
b'yahoo.com, 29284317597, DIRECT\n'
b'yahoo.com, 29284317598, DIRECT\n'
b'yahoo.com, 29284317596, DIRECT\n'
b'yahoo.com, 54978, DIRECT #banner\n'
b'yahoo.com, 55593, DIRECT #AOL, EMEA\n'
b'\n'
b'#AdX\n'
b'google.com, pub-7382640443023261, RESELLER, f08c47fec0942fa0 #banner, video, EMEA\n'
b'\n'
b'#DailyMotion\n'
b'nsightvideo.com, 143842749, DIRECT, fd25240165056a01 #video daily motion\n'
b'appnexus.com, 1824750, RESELLER #video daily motion\n'
b'google.com, pub-1386280613967939, RESELLER, f08c47fec0942fa0 #video daily motion\n'
b'google.com, pub-7019376976432612, RESELLER, f08c47fec0942fa0 #video daily motion\n'
b'districtm.io, 100025, RESELLER, 3fd707be9c4527c3\n'
b'\n'
b'#GroupM\n'
b'appnexus.com, 2127, RESELLER, f5ab79cb980f11d1\n'
b'appnexus.com, 3310, RESELLER, f5ab79cb980f11d1\n'
b'\n'
b'#Index\n'
b'indexexchange.com, 184349, RESELLER, 50b1c356f2c5c8fc #banner, EMEA\n'
b'indexexchange.com, 185232, RESELLER, 50b1c356f2c5c8fc #video, EMEA\n'
b'indexexchange.com, 175407, RESELLER #banner\n'
b'\n'
b'#OpenX\n'
b'openx.com, 539088779, RESELLER, 6a698e2ec38604c6 #banner, video, EMEA\n'
b'\n'
b'#Pubmatic\n'
b'pubmatic.com, 155967, RESELLER, 5d62403b186f2ace #banner, EMEA\n'
b'pubmatic.com, 156275, RESELLER, 5d62403b186f2ace #video, EMEA\n'
b'pubmatic.com, 156377, RESELLER, 5d62403b186f2ace #banner\n'
b'pubmatic.com, 156325, RESELLER, 5d62403b186f2ace #video\n'
b'pubmatic.com, 156556, RESELLER, 5d62403b186f2ace\n'
b'pubmatic.com, 160048, RESELLER, 5d62403b186f2ace\n'
b'\n'
b'#RichAudience\n'
b'pubmatic.com, 81564, RESELLER, 5d62403b186f2ace\n'
b'richaudience.com, 9cl16m9ADS, RESELLER\n'
b'\n'
b'#Rubicon\n'
b'rubiconproject.com, 9061, RESELLER, 0bfd66d529a55807 #banner, EMEA\n'
b'rubiconproject.com, 10061, RESELLER, 0bfd66d529a55807 #banner, DE\n'
b'\n'
b'#SkyMedia\n'
b'google.com, pub-8083473147275045, DIRECT, f08c47fec0942fa0\n'
b'google.com, ca-mb-app-pub-8083473147275045, RESELLER, f08c47fec0942fa0\n'
b'pubmatic.com,160470 ,DIRECT,5d62403b186f2ace\n'
b'indexexchange.com, 190802, RESELLER\n'
b'\n'
b'#TwiagoGmbH\n'
b'twiago.com, 211, RESELLER\n'
b'twiago.com, 865, RESELLER\n'
b'\n'
b'#VAN Zoomin.Tv\n'
b'freewheel.tv, 470113, RESELLER\n'
b'freewheel.tv, 470129, RESELLER\n'
b'\n'
b'#VAN Time\n'
b'google.com, pub-7363566645038776, RESELLER, f08c47fec0942fa0 #video, US\n'
b'google.com, pub-4294323687078806, RESELLER\n'
b'spotx.tv, 113481, RESELLER, 7842df1d2fe2db34\n'
b'\n'
b'#VAN IP Germany\n'
b'smartclip.net, 8225, RESELLER\n'
b'spotx.tv, 106817, RESELLER\n'
b'spotx.tv, 152009, RESELLER\n'
b'spotx.tv, 207262, RESELLER\n'
b'spotx.tv, 136947, RESELLER\n'
b'spotx.tv, 113481, RESELLER\n'
b'google.com, pub-3057818873023700, RESELLER\n'
b'appnexus.com, 3528, RESELLER\n'
b'appnexus.com, 1851, RESELLER\n'
b'appnexus.com, 3741, RESELLER\n'
b'appnexus.com, 9242, RESELLER\n'
b'aps.amazon.com, 3137, RESELLER\n'
b'spotx.tv, 149950, RESELLER, 7842df1d2fe2db34 #smartclip\n'
b'\n'
b'#VAN The Gaurdian\n'
b'google.com, pub-2012933198307164, RESELLER, f08c47fec0942fa0 #theguardian.com\n'
b'\n'
b'#VAN Immediate Media\n'
b'google.com, pub-4449341246402301, RESELLER, f08c47fec0942fa0 #VIDEO\n'
b'\n'
b'#VAN Goldbach Germany - German VS\n'
b'smartclip.net, 894, RESELLER #smartclip\n'
b'appnexus.com, 7445, RESELLER #IPD Xaxis\n'
b'openx.com, 537148817, RESELLER, 6a698e2ec38604c6\n'
b'appnexus.com, 8904, RESELLER\n'
b'\n'
b'#VAN Celebrity Wire\n'
b'spotx.tv, 244504, DIRECT, 7842df1d2fe2db34\n'
b'spotxchange.com, 244504, DIRECT, 7842df1d2fe2db34\n'
b'\n'
b'#VAN SmartClip\n'
b'smartclip.net, 11976, DIRECT\n'
b'\n'
b'#LATAM\n'
b'\n'
b'#LATAM Direct\n'
b'yahoo.com, 53717, DIRECT\n'
b'btrll.com, 6836418, DIRECT #video, LATAM\n'
b'yahoo.com, 25012495257, DIRECT #banner, ARGENTINA\n'
b'yahoo.com, 25147317336, DIRECT #banner, VENEZUELA\n'
b'yahoo.com, 25358466073, DIRECT #banner, PERU\n'
b'yahoo.com, 25771847929, DIRECT #banner, MEXICO\n'
b'yahoo.com, 25799949562, DIRECT #banner, ESPANOL\n'
b'yahoo.com, 26578611641, DIRECT #banner, BRAZIL\n'
b'yahoo.com, 28049787252, DIRECT #banner, COLOMBIA\n'
b'advertising.com, 23751, DIRECT #video, BR\n'
b'advertising.com, 24568, DIRECT #video, LATAM\n'
b'advertising.com, 28282, DIRECT\n'
b'advertising.com, 28270, DIRECT #LATAM\n'
b'\n'
b'#AdX\n'
b'google.com, pub-6473827730281113, RESELLER #banner, video, LATAM\n'
b'\n'
b'#Index\n'
b'indexexchange.com, 199936, RESELLER, 50b1c356f2c5c8fc\n'
b'indexexchange.com, 199974, RESELLER, 50b1c356f2c5c8fc\n'
b'\n'
b'#Pubmatic\n'
b'pubmatic.com, 157292, DIRECT, 5d62403b186f2ace\n'
b'\n'
b'#LKQD\n'
b'lkqd.net, 522, DIRECT, 59c49fa9598a0117\n'
b'\n'
b'#Rubicon\n'
b'rubiconproject.com, 12052, DIRECT, 0bfd66d529a55807 #banner, BRAZIL\n'
b'rubiconproject.com, 14060, DIRECT, 0bfd66d529a55807 #banner, LATAM\n'
b'\n'
b'#AUNZ\n'
b'\n'
b'#AUNZ Direct\n'
b'yahoo.com, 53626, DIRECT\n'
b'yahoo.com, 27900383901, DIRECT #banner, AU\n'
b'yahoo.com, 26157456305, DIRECT #banner, NZ\n'
b'advertising.com, 26657, DIRECT #video, AU\n'
b'\n'
b'#AdX\n'
b'google.com, pub-2149773675369613, RESELLER #banner, video, AU\n'
b'google.com, pub-6763722328147142, RESELLER #banner, video, NZ\n'
b'\n'
b'#Pubmatic\n'
b'pubmatic.com, 157840, RESELLER, 5d62403b186f2ace #banner, AUNZ\n'
b'\n'
b'#Tremor\n'
b'tremorhub.com, qyksj, RESELLER, 1a4e959a1b50034a #video\n'
b'tremorhub.com, qt78n-bdbnh, RESELLER, 1a4e959a1b50034a #video\n'
b'\n'
b'#APAC\n'
b'\n'
b'#APAC Direct\n'
b'yahoo.com, 53600, DIRECT\n'
b'yahoo.com, 53613, DIRECT\n'
b'yahoo.com, 28261959434, DIRECT #banner, TW\n'
b'yahoo.com, 29284317588, DIRECT #banner, APAC\n'
b'yahoo.com, 25533108522, DIRECT #banner, HK\n'
b'yahoo.com, 29284317511, DIRECT #banner, APAC\n'
b'yahoo.com, 26532719555, DIRECT #banner, IN\n'
b'yahoo.com, 27340194012, DIRECT #banner, PH\n'
b'yahoo.com, 29284317589, DIRECT #banner, APAC\n'
b'yahoo.com, 27743575868, DIRECT #banner, ID\n'
b'yahoo.com, 28906310396, DIRECT #banner, MY\n'
b'yahoo.com, 26177459484, DIRECT #banner, VN\n'
b'yahoo.com, 25225873693, DIRECT #banner, SG\n'
b'yahoo.com, 25306537877, DIRECT #banner, TH\n'
b'yahoo.com, 26055890550, DIRECT #banner, APAC\n'
b'yahoo.com, 29284317564, DIRECT #banner, SG\n'
b'yahoo.com, 29284317592, DIRECT #banner, APAC\n'
b'yahoo.com, 29284317525, DIRECT #banner, APAC\n'
b'advertising.com, 24444, DIRECT #video, APAC\n'
b'advertising.com, 8232, DIRECT #video, JP\n'
b'yahoo.com, 1024717, DIRECT #native\n'
b'yahoo.com, 1656752, DIRECT #native\n'
b'yahoo.com, 1652616, DIRECT #native\n'
b'yahoo.com, 991644, DIRECT #native\n'
b'aol.com, 48088, DIRECT\n'
b'yahoo.com, 58533, DIRECT #banner\n'
b'yahoo.com, 58554, DIRECT #banner\n'
b'yahoo.com, 58557, DIRECT #banner\n'
b'btrll.com, 6836232, DIRECT #video, APAC\n'
b'btrll.com, 6836231, DIRECT #video, APAC\n'
b'advertising.com, 24855, RESELLER #video, TW\n'

In [20]:
import pandas as pd
cols = ['Domain','Code','Type','Source']
df = pd.read_fwf(r'C:\Users\siddi\Desktop\addata.txt', 
                 header=None, delimiter=",",
                 names=cols)

In [21]:
df.head(10)

                                     Domain  Code  Type  Source
0                               #2022-06-09   NaN   NaN     NaN
1                # ownerdomain=yahooinc.com   NaN   NaN     NaN
2                                      #NAR   NaN   NaN     NaN
3                               #NAR Direct   NaN   NaN     NaN
4  advertising.com, 3679, DIRECT #video, US   NaN   NaN     NaN
5            advertising.com, 28090, DIRECT   NaN   NaN     NaN
6              yahoo.com, 1, DIRECT #native   NaN   NaN     NaN
7  yahoo.com, 52469, DIRECT #display, Yahoo   NaN   NaN     NaN
8    yahoo.com, 57316, DIRECT #display, AOL   NaN   NaN     NaN
9    yahoo.com, 57322, DIRECT #display, AOL   NaN   NaN     NaN

In [13]:
df_grouped = df.groupby(['Domain', 'Type']).size()

In [14]:
df_grouped

Domain  Type
# owne  in=yaho    1
#APAC   t          1
#AUNZ   t          1
#Daily  n          1
#EMEA   t          1
                  ..
yahoo.  991644,    1
yieldm  , 22094    1
        , 27240    1
        , 27376    1
        , 28253    1
Length: 360, dtype: int64

In [9]:
    def reverseWords(s):
        """
        :type s: str
        :rtype: str
        """
        words = s.split(' ')
        
        ans = ""
    
        for w in words:
            ans + w[::-1] + ''
        return ans[0:len(ans) - 1]

In [12]:
print(reverseWords('Let\'s take LeetCode contest'))

In [14]:
import pandas as pd

df = pd.read_csv(r"c:\Users\siddi\Downloads\russia_losses_equipment.csv")

In [15]:
df.head(3)

,date,day,aircraft,helicopter,tank,APC,field artillery,MRL,military auto,fuel tank,drone,naval ship,anti-aircraft warfare,special equipment,mobile SRBM system,greatest losses direction,vehicles and fuel tanks,cruise missiles
0,2022-02-25,2,10,7,80,516,49,4,100.0,60.0,0,2,0,NaN,NaN,NaN,NaN,NaN
1,2022-02-26,3,27,26,146,706,49,4,130.0,60.0,2,2,0,NaN,NaN,NaN,NaN,NaN
2,2022-02-27,4,27,26,150,706,50,4,130.0,60.0,2,2,0,NaN,NaN,NaN,NaN,NaN

In [17]:
df2 = pd.read_csv(r"c:\Users\siddi\Downloads\russia_losses_personnel.csv")

In [18]:
df2.head(3)

         date  day  personnel personnel*  POW
0  2022-02-25    2       2800      about  0.0
1  2022-02-26    3       4300      about  0.0
2  2022-02-27    4       4500      about  0.0

In [1]:
list1 = [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]
mean = sum(list1)/len(list1)
print(mean)

20.2

In [2]:
list1 = [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]
list1.sort()

if len(list1) % 2 == 0:
    m1 = list1[len(list1)//2]
    m2 = list1[len(list1)//2 - 1]
    median = (m1 + m2)/2
else:
    median = list1[len(list1)//2]
print(median)

20.0

In [3]:
list1 = [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]
frequency = {}
for i in list1:
    frequency.setdefault(i, 0)
    frequency[i]+=1

frequent = max(frequency.values())
for i, j in frequency.items():
    if j == frequent:
        mode = i
print(mode)

20

In [9]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv(r"C:\Users\siddi\Downloads\netflixData.csv\netflixData.csv")
print(data.head())

                                Show Id                          Title  \
0  cc1b6ed9-cf9e-4057-8303-34577fb54477                       (Un)Well
1  e2ef4e91-fb25-42ab-b485-be8e3b23dedb                         #Alive
2  b01b73b7-81f6-47a7-86d8-acb63080d525  #AnneFrank - Parallel Stories
3  b6611af0-f53c-4a08-9ffa-9716dc57eb9c                       #blackAF
4  7f2d4170-bab8-4d75-adc2-197f7124c070               #cats_the_mewvie

                                         Description  \
0  This docuseries takes a deep dive into the luc...
1  As a grisly virus rampages a city, a lone man ...
2  Through her diary, Anne Frank's story is retol...
3  Kenya Barris and his family navigate relations...
4  This pawesome documentary explores how our fel...

                      Director  \
0                          NaN
1                       Cho Il
2  Sabina Fedeli, Anna Migotto
3                          NaN
4             Michael Margolis

                                           Genres  \
0                                      Reality TV
1  Horror Movies, International Movies, Thrillers
2             Documentaries, International Movies
3                                     TV Comedies
4             Documentaries, International Movies

                                                Cast Production Country  \
0                                                NaN      United States
1                           Yoo Ah-in, Park Shin-hye        South Korea
2                        Helen Mirren, Gengher Gatti              Italy
3  Kenya Barris, Rashida Jones, Iman Benson, Genn...      United States
4                                                NaN             Canada

   Release Date Rating  Duration Imdb Score Content Type         Date Added
0        2020.0  TV-MA  1 Season     6.6/10      TV Show                NaN
1        2020.0  TV-MA    99 min     6.2/10        Movie  September 8, 2020
2        2019.0  TV-14    95 min     6.4/10        Movie       July 1, 2020
3        2020.0  TV-MA  1 Season     6.6/10      TV Show                NaN
4        2020.0  TV-14    90 min     5.1/10        Movie   February 5, 2020

In [10]:
print(data.isnull().sum())

Show Id                  0
Title                    0
Description              0
Director              2064
Genres                   0
Cast                   530
Production Country     559
Release Date             3
Rating                   4
Duration                 3
Imdb Score             608
Content Type             0
Date Added            1335
dtype: int64

In [11]:
data = data[["Title", "Description", "Content Type", "Genres"]]
print(data.head())

                           Title  \
0                       (Un)Well
1                         #Alive
2  #AnneFrank - Parallel Stories
3                       #blackAF
4               #cats_the_mewvie

                                         Description Content Type  \
0  This docuseries takes a deep dive into the luc...      TV Show
1  As a grisly virus rampages a city, a lone man ...        Movie
2  Through her diary, Anne Frank's story is retol...        Movie
3  Kenya Barris and his family navigate relations...      TV Show
4  This pawesome documentary explores how our fel...        Movie

                                           Genres
0                                      Reality TV
1  Horror Movies, International Movies, Thrillers
2             Documentaries, International Movies
3                                     TV Comedies
4             Documentaries, International Movies

In [12]:
data = data.dropna()

In [13]:
import nltk
import re
nltk.download('stopwords')
stemmer = nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
import string
stopword=set(stopwords.words('english'))

def clean(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text
data["Title"] = data["Title"].apply(clean)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\siddi\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [14]:
print(data.Title.sample(10))

5793                    what raashe
3549                      oper ouch
5429    tom papa live new york citi
4216                     shes gotta
375                           anima
4583           termin  judgment day
950                           cheer
340                ami schumer grow
4586      terrac hous open new door
3494                       okko inn
Name: Title, dtype: object

In [15]:
feature = data["Genres"].tolist()
tfidf = text.TfidfVectorizer(input=feature, stop_words="english")
tfidf_matrix = tfidf.fit_transform(feature)
similarity = cosine_similarity(tfidf_matrix)

In [16]:
indices = pd.Series(data.index, 
                    index=data['Title']).drop_duplicates()

In [17]:
def netFlix_recommendation(title, similarity = similarity):
    index = indices[title]
    similarity_scores = list(enumerate(similarity[index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores = similarity_scores[0:10]
    movieindices = [i[0] for i in similarity_scores]
    return data['Title'].iloc[movieindices]

print(netFlix_recommendation("girlfriend"))

3                          blackaf
285                     washington
417                 arrest develop
434     astronomi club sketch show
451    aunti donna big ol hous fun
656                      big mouth
752                bojack horseman
805                   brew brother
935                       champion
937                  chappell show
Name: Title, dtype: object

In [4]:
import pandas as pd
import yfinance as yf
import datetime
from datetime import date, timedelta
today = date.today()

d1 = today.strftime("%Y-%m-%d")
end_date = d1
d2 = date.today() - timedelta(days=360)
d2 = d2.strftime("%Y-%m-%d")
start_date = d2

data = yf.download('AAPL', 
                      start=start_date, 
                      end=end_date, 
                      progress=False)
print(data.head())

                                 Open        High         Low       Close  \
Date
2021-10-11 00:00:00-04:00  142.270004  144.809998  141.809998  142.809998
2021-10-12 00:00:00-04:00  143.229996  143.250000  141.039993  141.509995
2021-10-13 00:00:00-04:00  141.240005  141.399994  139.199997  140.910004
2021-10-14 00:00:00-04:00  142.110001  143.880005  141.509995  143.759995
2021-10-15 00:00:00-04:00  143.770004  144.899994  143.509995  144.839996

                            Adj Close    Volume
Date
2021-10-11 00:00:00-04:00  142.014206  64452200
2021-10-12 00:00:00-04:00  140.721451  73035900
2021-10-13 00:00:00-04:00  140.124802  78762700
2021-10-14 00:00:00-04:00  142.958923  69907100
2021-10-15 00:00:00-04:00  144.032898  67940300

In [3]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-0.1.75-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\siddi\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pandas>=0.24.0 in c:\users\siddi\anaconda3\lib\site-packages (from yfinance) (1.4.2)
Requirement already satisfied: lxml>=4.5.1 in c:\users\siddi\anaconda3\lib\site-packages (from yfinance) (4.8.0)
Requirement already satisfied: numpy>=1.15 in c:\users\siddi\anaconda3\lib\site-packages (from yfinance) (1.21.5)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: requests>=2.26 in c:\users\siddi\anaconda3\lib\site-packages (from yfinance) (2.27.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\siddi\anaconda3\lib\site-packages (from pandas>=0.24.0->yfinance) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\siddi\anaconda3\lib\site-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\siddi\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.24.0->yfinance) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\siddi\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\siddi\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\siddi\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\siddi\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (1.26.9)
Installing collected packages: multitasking, yfinance
Successfully installed multitasking-0.0.11 yfinance-0.1.75
Note: you may need to restart the kernel to use updated packages.

In [5]:
import plotly.express as px
figure = px.line(data, x = data.index, y = "Close")
figure.show()

In [6]:
import pandas as pd
import yfinance as yf
import datetime
from datetime import date, timedelta
today = date.today()

d1 = today.strftime("%Y-%m-%d")
end_date = d1
d2 = date.today() - timedelta(days=360)
d2 = d2.strftime("%Y-%m-%d")
start_date = d2

data = yf.download('AAPL', 
                      start=start_date, 
                      end=end_date, 
                      progress=False)
print(data.head())

                                 Open        High         Low       Close  \
Date
2021-10-11 00:00:00-04:00  142.270004  144.809998  141.809998  142.809998
2021-10-12 00:00:00-04:00  143.229996  143.250000  141.039993  141.509995
2021-10-13 00:00:00-04:00  141.240005  141.399994  139.199997  140.910004
2021-10-14 00:00:00-04:00  142.110001  143.880005  141.509995  143.759995
2021-10-15 00:00:00-04:00  143.770004  144.899994  143.509995  144.839996

                            Adj Close    Volume
Date
2021-10-11 00:00:00-04:00  142.014206  64452200
2021-10-12 00:00:00-04:00  140.721451  73035900
2021-10-13 00:00:00-04:00  140.124802  78762700
2021-10-14 00:00:00-04:00  142.958908  69907100
2021-10-15 00:00:00-04:00  144.032898  67940300

In [7]:
data["Date"] = data.index
data = data[["Date", "Open", "High", 
             "Low", "Close", "Adj Close", "Volume"]]
data.reset_index(drop=True, inplace=True)
print(data.head())

                       Date        Open        High         Low       Close  \
0 2021-10-11 00:00:00-04:00  142.270004  144.809998  141.809998  142.809998
1 2021-10-12 00:00:00-04:00  143.229996  143.250000  141.039993  141.509995
2 2021-10-13 00:00:00-04:00  141.240005  141.399994  139.199997  140.910004
3 2021-10-14 00:00:00-04:00  142.110001  143.880005  141.509995  143.759995
4 2021-10-15 00:00:00-04:00  143.770004  144.899994  143.509995  144.839996

    Adj Close    Volume
0  142.014206  64452200
1  140.721451  73035900
2  140.124802  78762700
3  142.958908  69907100
4  144.032898  67940300

In [9]:
import plotly.graph_objects as go
figure = go.Figure(data=[go.Candlestick(x=data["Date"],
                                        open=data["Open"], 
                                        high=data["High"],
                                        low=data["Low"], 
                                        close=data["Close"])])
figure.update_layout(title = "Apple Stock Price Analysis", 
                     xaxis_rangeslider_visible=False)
figure.show()